name = "json_blueprint"
version = "1.6.0"

description = "Simplify JSON encoding/decoding while automatically generating JSON schemas for your data types."
licences = ["MIT"]
repository = { type = "github", user = "lostbean", repo = "json_blueprint" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 3.0.0"
gleam_crypto = ">= 1.3.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
